# Generated by Django 4.0.6 on 2022-10-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('characteristics', models.TextField(blank=True, verbose_name='Characteristics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('image', models.ImageField(upload_to='Mod/image', verbose_name='Image')),
            ],
        ),
    ]
