# Generated by Django 4.0.6 on 2022-10-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl0g', '0002_categories_alter_mod_options_mod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='characteristics',
            field=models.TextField(blank=True, verbose_name='characteristics'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='image',
            field=models.ImageField(upload_to='Mod/image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
    ]
