# Generated by Django 4.0.6 on 2022-10-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl0g', '0003_alter_mod_characteristics_alter_mod_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': [], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='mod',
            name='price',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
    ]
